<Project>
    <PropertyGroup>
        <ValheimGamePath Condition="'$(ValheimGamePath)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimGamePath>
        <BepInExPath>$(ValheimGamePath)\BepInEx</BepInExPath>
        <CorlibPath>$(ValheimGamePath)\valheim_Data\Managed</CorlibPath>
        <PublicizedAssembliesPath>$(ValheimGamePath)\valheim_Data\Managed\publicized_assemblies</PublicizedAssembliesPath>
        <JotunnPath Condition="'$(JotunnPath)' == '' And Exists('$(BepInExPath)\plugins\Jotunn.dll')">$(BepInExPath)\plugins\Jotunn.dll</JotunnPath>
        <JotunnPath Condition="'$(JotunnPath)' == '' And Exists('$(BepInExPath)\plugins\ValheimModding-Jotunn\Jotunn.dll')">$(BepInExPath)\plugins\ValheimModding-Jotunn\Jotunn.dll</JotunnPath>
        <CopyOutputDLLPath>$(ValheimGamePath)\BepInEx\plugins</CopyOutputDLLPath>
    </PropertyGroup>
</Project>
